version: '3.8'
services:
  db:
    image: enmotech/opengauss-lite:latest
    container_name: opengauss
    privileged: true
    environment:
      - GS_PASSWORD=Secretpassword@123
      - GS_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/opengauss
  web:
    build: .
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=gaussdb
      - DB_PASSWORD=Secretpassword@123
      - DB_DATABASE=postgres
    ports:
      - "3000:3000"
volumes:
  db-data:

